### ISSUE TITLE
layout: default not working

### ISSUE THREAD

**Issue by sandheather** [sandheather/Portfolio#1]
@ericadamski

Hi Eric,
The only page that seems to be working with layout: default is artdeco.html. When I try to click on the other portfolio pieces they go to a 404 page. I've written to code exactly the same on each html page so I'm not quite sure whats wrong. Hopefully you can help me out.
Thanks,
Heather
<img width="645" alt="screen shot 2016-11-14 at 9 09 30 am" src="https://cloud.githubusercontent.com/assets/10467705/20267742/1ecf521a-aa4a-11e6-82db-2a04ab16d8d2.png">

**Comment by ericadamski** [comment]
@sandheather try remove the `.html` in the links. for example the above example would be

```
sandheather.github.io/portfolio/movieposter/
```

Let me know if that doesn't work :)

**Comment by sandheather** [comment]
yes it works. thank you so much! 
I see know in the index.html that you had removed the .html from the artdeco link when we were working on it in class.
