### ISSUE TITLE
Class

### ISSUE THREAD

**Issue by sandheather** [sandheather/Portfolio#3]
@ericadamski
Hi Eric, 
Sorry to bug you but I sent you a message on canvas and I hope to get a message before class :/
Thanks,
Heather

**Comment by ericadamski** [comment]
Just send me a screen snap of the security sniper :)

**Comment by sandheather** [comment]
@ericadamski 
<img width="1439" alt="screen shot 2016-12-16 at 1 34 04 pm" src="https://cloud.githubusercontent.com/assets/10467705/21274786/e75c4ac4-c397-11e6-9736-a4f4e097a2f3.png">

**Comment by sandheather** [comment]
@ericadamski 
Thank you very much
